// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOrA6EhWeJs42guL8n79ootnF-KiK-v4o',
    appId: '1:266728357187:web:WEBAPPID',
    messagingSenderId: '266728357187',
    projectId: 'notaok-4d791',
    authDomain: 'notaok-4d791.firebaseapp.com',
    storageBucket: 'notaok-4d791.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOrA6EhWeJs42guL8n79ootnF-KiK-v4o',
    appId: '1:266728357187:android:2b8f1eed8cf2ff72e703f6',
    messagingSenderId: '266728357187',
    projectId: 'notaok-4d791',
    storageBucket: 'notaok-4d791.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOrA6EhWeJs42guL8n79ootnF-KiK-v4o',
    appId: '1:266728357187:ios:IOSAPPID',
    messagingSenderId: '266728357187',
    projectId: 'notaok-4d791',
    storageBucket: 'notaok-4d791.firebasestorage.app',
    iosBundleId: 'com.warrantywizard.warranty',
  );
}
